name: Build Project
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - audio
          - audio_recorder
          - clock
          - hardware_test
          - light_dial_game
          - light_show
          - wifi_sniffer
          # - y-board-v2/hardware_test
          # - y-board-v2/homekit
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Project
        run: pio run
        working-directory: ./y-board-v3/${{ matrix.project }}

      - name: Make binary
        run: python3 build.py ${{ matrix.project }}
        working-directory: ./y-board-v3

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.project }}.bin
          path: ./y-board-v3/build
