name: Build and Deploy v4 Projects
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          # - test_io
          # - light_dial_game
          # - light_show
          # - ir
          # - hardware_test
          # - color_game
          # - clock
          - audio_recorder
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build Project
        run: pio run
        working-directory: ./y-board-v4/${{ matrix.project }}

  deploy:
    name: Deploy to demo-flasher
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/test-deploy'
    steps:
      - name: Checkout demo-code repo
        uses: actions/checkout@v4

      - name: Collect Artifacts
        run: |
          mkdir -p out
          for project in audio_recorder; do
            ls -ahl .
            ls -ahl ./y-board-v4/$project
            python3 ./y-board-v4/build.py --only-merge ./y-board-v4/$project
            cp ./y-board-v4/build/$project.bin out/ || true
          done
